name: Build packages and store artifacts

on:

  workflow_dispatch:
    inputs:
      version-suffix:
        type: string
        description: 'semver version suffix'
        required: false
        default: ''

  workflow_call:
    inputs:
      version-suffix:
        type: string
        description: 'semver version suffix'
        required: true
        default: ''
    
jobs:
  build_job:

    runs-on: ubuntu-latest    
    timeout-minutes: 5

    steps:   

      # ---------------------------------------------  DotNet SDK

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

      # ---------------------------------------------  checkout repo

    - name: Checkout
      uses: actions/checkout@v4
      
      # ---------------------------------------------  variables

    - name: define version suffix 1
      if: ${{ env.VERSIONSUFFIX == '' }}
      run: echo "VERSIONSUFFIX=${{ inputs.version-suffix }}" >> $GITHUB_ENV

    - name: define version suffix 2
      if: ${{ env.VERSIONSUFFIX == '' }}
      run: echo "VERSIONSUFFIX=Test-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # ---------------------------------------------  build

    - name: Install tools
      run: dotnet tool restore

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --version-suffix ${{ env.VERSIONSUFFIX }}
    
    - name: Pack
      run: dotnet pack -c Release --no-build --output "."

      # ---------------------------------------------  publish

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        retention-days: 1
        path: |
            *.nupkg
            *.snupkg